## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

application_df = application_df.drop(columns = ['EIN', 'NAME'], axis = 1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE

application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
v_counts = application_df['APPLICATION_TYPE'].value_counts()

In [8]:
from IPython.core import application
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cut_off_value = 500
application_types_to_replace = []

# Value count for each application type
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Create a list of application types to be replaced
for app_type, count in application_type_counts.items():
  if count < cut_off_value:
    application_types_to_replace.append(app_type)

# Replace the data frame
for app in application_types_to_replace:
  application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, 'Other')

application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

classif_counts = application_df['CLASSIFICATION'].value_counts()
classif_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

classif_counts_filtered = classif_counts[classif_counts > 1]
classif_counts_filtered

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1000
classifications_to_replace = []

classification_counts = application_df['CLASSIFICATION'].value_counts()

for cls, count in classification_counts.items():
  if count < cutoff_value:
    classifications_to_replace.append(cls)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
from numpy.random.mtrand import random
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df['IS_SUCCESSFUL'].values
y

X = application_df.drop('IS_SUCCESSFUL', axis = 1).values
X
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
from keras.api._v2.keras import activations
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_of_inputs = len(X_train_scaled[0])
hidden_node_one = 35
hidden_node_two = 18

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units = hidden_node_one, input_dim = number_of_inputs, activation = 'relu'))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units = hidden_node_two, activation = 'relu'))


# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 35)                1540

 dense_1 (Dense)             (None, 18)                648

 dense_2 (Dense)             (None, 1)                 19

=================================================================
Total params: 2,207
Trainable params: 2,207
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Compile the model
#  YOUR CODE GOES HERE

nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [17]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("model_weights.h5", save_weights_only = True, period = 5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [20]:
# Train the model
#  YOUR CODE GOES HERE

fit_model = nn.fit(X_train, y_train, epochs = 100, callbacks = [checkpoint])

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 29753.3867 - accuracy: 0.4902
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 58690.8555 - accuracy: 0.4862
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 41190.4531 - accuracy: 0.5044
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 11689.8389 - accuracy: 0.5041
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 5469.0220 - accuracy: 0.5163
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 28538.4277 - accuracy: 0.5138
Epoch 7/100
804/804 [==============================] - 4s 5ms/step - loss: 6548.6548 - accuracy: 0.5124
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 60862.8242 - accuracy: 0.4929
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 18016.4121 - accuracy: 0.4884
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 3174.1997 - accuracy: 0.5085
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 37441.6562 - accuracy: 0.5003
Epoch 12/100
804/804 [==============================] - 4s 5ms/step - loss: 19668.1758 - accuracy: 0.5362
Epoch 13/100
804/804 [==============================] - 3s 3ms/step - loss: 20083.4922 - accuracy: 0.5121
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 12922.9355 - accuracy: 0.5065
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 13878.8809 - accuracy: 0.5224
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 22002.9629 - accuracy: 0.5249
Epoch 17/100
804/804 [==============================] - 4s 4ms/step - loss: 9792.9873 - accuracy: 0.5295
Epoch 18/100
804/804 [==============================] - 3s 4ms/step - loss: 9951.7070 - accuracy: 0.5398
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 10383.9590 - accuracy: 0.5489
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 10544.0801 - accuracy: 0.5285
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 10851.5029 - accuracy: 0.5356
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 6020.4810 - accuracy: 0.5308
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 9955.1182 - accuracy: 0.5214
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 5741.8232 - accuracy: 0.5450
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 4857.4380 - accuracy: 0.5640
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 1006.6298 - accuracy: 0.5454
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 5230.3530 - accuracy: 0.5110
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 4572.0117 - accuracy: 0.5113
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 3435.3376 - accuracy: 0.5179
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 2160.0664 - accuracy: 0.5250
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 1207.8448 - accuracy: 0.4362
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 709.7868 - accuracy: 0.5116
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 1296.6099 - accuracy: 0.5295
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 18.4994 - accuracy: 0.5335
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 8.6993 - accuracy: 0.5275
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6849 - accuracy: 0.5318
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6788 - accuracy: 0.5318
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6727 - accuracy: 0.5318
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6667 - accuracy: 0.5806
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6603 - accuracy: 0.6556
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6525 - accuracy: 0.6677
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6974 - accuracy: 0.5205
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5318
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5318
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5318

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.8164 - accuracy: 0.6957 - 493ms/epoch - 2ms/step
Loss: 0.8163620829582214, Accuracy: 0.6957434415817261

In [22]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE

nn.save('AlphabetSoupCharity.h5')